=== cracksoft-corp/newsletter-generation/content-output.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Newsletter Episode Schema",
    "type": "object",
    "properties": {
      "$schema": {
        "type": "string"
      },
      "episode": {
        "type": "object",
        "properties": {
          "number": {
            "type": "integer"
          },
          "date": {
            "type": "string"
          },
          "title": {
            "type": "string"
          }
        },
        "required": [
          "number",
          "date",
          "title"
        ],
        "additionalProperties": false
      },
      "intro": {
        "type": "string"
      },
      "showNotes": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "quickfireQuestions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "breakingProdLeaderboard": {
        "type": "object",
        "properties": {
          "summary": {
            "type": "string"
          }
        },
        "required": [
          "summary"
        ],
        "additionalProperties": false
      },
      "bigTopic": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string"
          },
          "questions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "title",
          "questions"
        ],
        "additionalProperties": false
      },
      "news": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "items": {
              "type": "object",
              "properties": {
                "type": { "type": "string" },
                "title": { "type": "string" },
                "description": { "type": "string" },
                "uploadedImageUrl": { "type": "string", "format": "uri" },
                "url": { "type": "string", "format": "uri" },
                "buttonText": { "type": "string" },
                "buttonBackgroundColour": { "type": "string" },
                "buttonTextColour": { "type": "string" }
              },
              "required": [ "type", "title", "url", "description", "uploadedImageUrl", "buttonBackgroundColour", "buttonTextColour", "buttonText"],
              "additionalProperties": false
            }
          }
        }
      },
      "recommendations": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "sectionName": { "type": "string" },
            "displayName": { "type": "string" },
            "items": { "type": "array" }
          },
          "required": [ "sectionName", "displayName", "items" ],
          "oneOf": [
            {
              "if": {
                "properties": { "sectionName": { "const": "music" } }
              },
              "then": {
                "properties": {
                  "items": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "artist": { "type": "string" },
                        "album": { "type": "string" },
                        "description": { "type": "string" },
                        "uploadedImageUrl": { "type": "string", "format": "uri" },
                        "links": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "platform": { "type": "string" },
                              "url": { "type": "string", "format": "uri" }
                            },
                            "required": [ "platform", "url" ],
                            "additionalProperties": false
                          }
                        }
                      },
                      "required": [ "artist", "description", "uploadedImageUrl", "links" ],
                      "additionalProperties": false
                    }
                  }
                }
              },
              "else": { "not": {} }
            },
            {
              "if": {
                "properties": { "sectionName": { "const": "relatedTopic" } }
              },
              "then": {
                "properties": {
                  "items": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "type": { "type": "string" },
                        "title": { "type": "string" },
                        "authors": {
                          "type": "array",
                          "items": { "type": "string" }
                        },
                        "description": { "type": "string" },
                        "uploadedImageUrl": { "type": "string", "format": "uri" },
                        "url": { "type": "string", "format": "uri" },
                        "buttonText": { "type": "string" },
                        "buttonBackgroundColour": { "type": "string" },
                        "buttonTextColour": { "type": "string" }
                      },
                      "required": [ "type", "title", "url", "description", "uploadedImageUrl", "buttonBackgroundColour", "buttonTextColour", "buttonText"],
                      "additionalProperties": false
                    }
                  }
                }
              },
              "else": { "not": {} }
            },
            {
              "if": {
                "properties": { "sectionName": { "const": "tech" } }
              },
              "then": {
                "properties": {
                  "items": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "type": { "type": "string" },
                        "title": { "type": "string" },
                        "description": { "type": "string" },
                        "url": { "type": "string", "format": "uri" },
                        "uploadedImageUrl": { "type": "string", "format": "uri" },
                        "buttonText": { "type": "string" },
                        "buttonBackgroundColour": { "type": "string" },
                        "buttonTextColour": { "type": "string" }
                      },
                      "required": [ "title", "description", "url", "uploadedImageUrl", "buttonText", "buttonBackgroundColour", "buttonTextColour" ],
                      "additionalProperties": false
                    }
                  }
                }
              },
              "else": { "not": {} }
            },
            {
              "if": {
                "properties": { "sectionName": { "const": "tv_and_film" } }
              },
              "then": {
                "properties": {
                  "items": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "type": { "type": "string" },
                        "title": { "type": "string" },
                        "description": { "type": "string" },
                        "url": { "type": "string", "format": "uri" },
                        "uploadedImageUrl": { "type": "string", "format": "uri" },
                        "buttonText": { "type": "string" },
                        "buttonBackgroundColour": { "type": "string" },
                        "buttonTextColour": { "type": "string" }
                      },
                      "required": [ "title", "description", "url", "uploadedImageUrl", "buttonText", "buttonBackgroundColour", "buttonTextColour" ],
                      "additionalProperties": false
                    }
                  }
                }
              },
              "else": { "not": {} }
            },
            {
              "if": {
                "properties": { "sectionName": { "const": "books" } }
              },
              "then": {
                "properties": {
                  "items": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                          "type": { "type": "string" },
                          "title": { "type": "string" },
                          "description": { "type": "string" },
                          "uploadedImageUrl": { "type": "string", "format": "uri" },
                          "url": { "type": "string", "format": "uri" },
                          "buttonBackgroundColour": { "type": "string" },
                          "buttonTextColour": { "type": "string" },
                          "buttonText": { "type": "string" }
                        },
                        "required": [ "type", "title", "url", "description", "uploadedImageUrl", "buttonBackgroundColour", "buttonTextColour", "buttonText" ],
                        "additionalProperties": false
                    }
                  }
                }
              },
              "else": { "not": {} }
            },
            {
              "if": {
                "properties": { "sectionName": { "const": "podcasts" } }
              },
              "then": {
                "properties": {
                  "items": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "type": { "type": "string" },
                        "title": { "type": "string" },
                        "description": { "type": "string" },
                        "uploadedImageUrl": { "type": "string", "format": "uri" },
                        "url": { "type": "string", "format": "uri" },
                        "buttonBackgroundColour": { "type": "string" },
                        "buttonTextColour": { "type": "string" },
                        "buttonText": { "type": "string" }
                      },
                      "required": [ "type", "title", "url", "description", "uploadedImageUrl", "buttonBackgroundColour", "buttonTextColour", "buttonText" ],
                      "additionalProperties": false
                    }
                  }
                }
              },
              "else": { "not": {} }
            }
          ]
        }
      },
      "joke": {
        "type": "object",
        "properties": {
          "setup": { "type": "string" },
          "punchline": { "type": "string" }
        },
        "required": [ "setup", "punchline" ],
        "additionalProperties": false
      }
    },
    "required": [
      "episode",
      "intro",
      "showNotes",
      "quickfireQuestions",
      "breakingProdLeaderboard",
      "bigTopic",
      "news",
      "recommendations",
      "joke"
    ],
    "additionalProperties": false
  }

=== cracksoft-corp/newsletter-generation/episodes/14/content-input.json
{
    "$schema": "../../content-input.schema.json",
    "episode": {
      "number": 14,
      "date": "21st March",
      "title": "something"
    },
    "intro": "We've got Raxit Ramani, a highly experienced Agile Coach and Project Manager talking about Scaled Agile, SAFe, stories of things being wrong, and how different government bodies have operated in the past.",
    "showNotes": [
      "Michael is still pale after a weekend in the sun. He didn't shed a tear after being in the Spa's flotation tank",
      "Raxit had a good job interview"
    ],
    "quickfireQuestions": [
      "Your opinion of Agile, in one word?",
      "What‚Äôs the biggest crime when making container images?"
    ],
    "breakingProdLeaderboard": {
      "summary": "We have a new winner! With 3 distinct stories!"
    },
    "bigTopic": {
      "title": "DevOps & SRE conversations",
      "questions": [
        "How would you describe modern agile software development to a new developer?",
        "How does a department know when it‚Äôs ready for a scaled agile framework?"
      ]
    },
    "news": [
        {
            "url": "https://www.wiz.io/blog/new-github-action-supply-chain-attack-reviewdog-action-setup"
        },
        {
            "url": "https://www.helpnetsecurity.com/2025/03/18/google-acquire-wiz-32-billion/"
        },
        {
            "url": "https://www.techspot.com/news/107175-amazon-removing-option-local-alexa-processing-forcing-all.html"
        },
        {
            "url": "https://www.theguardian.com/technology/2025/mar/18/byd-ev-fast-charging-system-petrol-fuel-speed"
        }
    ],
    "recommendations": [
        {
          "sectionName": "relatedTopic",
          "displayName": "DevOps & SRE",
          "items": [
            {
              "type": "Website",
              "title": "A Tour of Go",
              "url": "https://scaledagile.com"
            },
            {
              "type": "Book",
              "title": "Release It!",
              "url": "https://pragprog.com/titles/mnee2/release-it-2nd-edition/"
            }
          ]
        },
        {
          "sectionName": "music",
          "displayName": "üéµ Music",
          "items": [
            {
              "artist": "Sharon Van Etten",
              "album": "Sharon Van Etten & The Attachment Theory"
            },
            {
              "artist": "The Bug Club"
            },
            {
              "artist": "Truthpaste"
            }
          ]
        },
        {
          "sectionName": "tv_and_film",
          "displayName": "üì∫ TV & Film üé¨",
          "items": [
            {
              "title": "School Swap: UK to USA",
              "url": "https://www.channel4.com/programmes/school-swap-uk-to-usa"
            },
            {
              "title": "Adolesence",
              "url": "https://www.netflix.com/gb/title/81756069"
            }
          ]
        },
        {
          "sectionName": "books",
          "displayName": "üìö Books",
          "items": [
            {
              "title": "The ART of Avoiding a Train Wreck: Practical Tips...",
              "authors": ["Em Campbell-Pretty", "Adrienne L. Wilson"],
              "url": "https://www.abebooks.co.uk/9781094752280"
            }
          ]
        },
        {
          "sectionName": "podcasts",
          "displayName": "üéôÔ∏è Podcasts",
          "items": [
            {
              "title": "Steering Engineering",
              "url": "https://steering-engineering-podcast.simplecast.com/"
            }
          ]
        }
    ],
    "joke": {
      "setup": "A man has been admitted to hospital with 12 small toy horses found inside his anus.",
      "punchline": "His condition has been described as stable."
    }
  }
